import React from 'react'
import Footer from './Footer'
import { Link } from 'react-router-dom'
import homePageMainImage from '../Assets/Images/homePageMainImage.png'
import HomeLayout from './HomeLayout'


function HomePage() {
    return (
        <HomeLayout>
            <div>
                <div className='w-full h-[90vh] bg-[#1d232a] flex justify-center items-center '>

                    <div className='flex flex-col mx-20 gap-4'>
                        <h1 className='text-[1cm] text-white font-bold'> Welcome to MLM System <span className='text-yellow-400'>Multi-Level Marketing</span></h1>
                        <p className='text-xl text-gray-300 '>Multi-Level Marketing (MLM): A business model where individuals earn commissions through direct sales and recruitment of others into the network. 
                        <br />
                        Revenue Generation: MLM relies on both personal sales and the sales generated by recruits at various levels, creating a tiered earning structure. </p>

                        <div className='flex gap-4 '>
                            <button className='border rounded-md bg-yellow-400 text-white hover:bg-yellow-500 hover:text-black p-2 text-semibold '>
                                <Link to="/Courses">Explore</Link>
                            </button>

                            <button className='border rounded-md p-2 text-semibold text-white hover:bg-yellow-400 hover:text-black'>
                                <Link to="/Contact Us ">Contact Us
                                </Link>
                            </button>


                        </div>


                    </div>

                    <div>
                        <img src={homePageMainImage} alt="HomePageImage " />
                    </div>


                </div>

                {/* <Footer /> */}
            </div>

        </HomeLayout>

    )
}

export default HomePage
